### ISSUE TITLE
Dynamic Fish Pond Tracking

### ISSUE THREAD

**Issue by Bartholomue** [Croutonic-Creations-Stardew/SDV-AccessibleTiles#50]
Placing a sign of the vessel on a fish pond displays what kind of fish is in the pond. Could this be reflected in the tracker by distinguishing fish ponds as separate entities? Rainbow Trout fish pond, for example, instead of just fish pond.
Distinguishing between ponds ready for harvest and ponds that have a fish quest so players can navigate to the correct object to handle it.

**Comment by GrumpyCrouton** [comment]
It would also need to be able to account for multiple of the same type of pond. So maybe like "Rainbow Trout Fish Pond", "Rainbow Trout Fish Pond 2", etc. Thoughts? @Bartholomue

**Comment by Bartholomue** [comment]
I don't actually think it needs to, If you start allowing for tracking multiples of the same fish pond, you'll be in over your head with  people wanting to track multiples of the same parsnip.... 100 times. If the fish ponds dynamically changed their status to ones with quests, ones with harvests, and regular. So a rainbow trout fish pond would be different from a tiger trout fish pond, and a harvestable tiger trout fish pond would be different from a quest tiger trout fish pont, but two rainbow trout fish ponds should be treated as most objects are now, with AT only listing the first / closest.

**Comment by Bartholomue** [comment]
Solved in Stardew Access.
